---
title: "rf_model"
output: html_document
date: "2022-12-01"
---

```{r setup, include=FALSE}
library(tidymodels)
library(tidyverse)
library(ggplot2)
library(vip)
library(ranger)
tidymodels_prefer()



load(file = '/Users/Sofia/Documents/GitHub/Final_Project_Airbnb/model_basics/model_setup.rda')
```

##Random Forest

Our final model is our most complex and long winded: the random forest. We will follow the same steps to set it up, and We will start by setting up the engine and the model:

```{r}
forest_spec <- rand_forest() %>% 
  set_engine("ranger", importance = 'impurity') %>% 
  set_mode("regression") %>% 
  set_args(mtry = tune(),
           trees = tune(),
           min_n = tune())
```

Then the workflow:

```{r}
forest_wf <- workflow() %>% 
  add_model(forest_spec) %>% 
  add_recipe(abnb_recipe)
```

Then the grid:

```{r}
param_grid_forest <- grid_regular(mtry(range = c(1,10)), min_n(range = c(5,20)),
                           trees(range = c(100, 500)), levels = 8)
```

And after all that we finish off by tuning the model:

```{r}
tune_forest <- tune_grid(
  forest_wf,
  resamples = abnb_folds,
  grid = param_grid_forest,
  metrics = metric_set(rmse, rsq)
)

write_rds(tune_forest, file = '/Users/Sofia/Documents/GitHub/Final_Project_Airbnb/results/rf_results')
```

```{r}
rf_results <- read_rds('/Users/Sofia/Documents/GitHub/Final_Project_Airbnb/results/rf_results')

final_forest_wf <- forest_wf %>% 
  finalize_workflow(select_best(rf_results))

forest_fit <- fit(final_forest_wf, data = abnb_tr) %>% extract_fit_parsnip()

rf_vip <- vip(forest_fit)
save(rf_vip, file = '/Users/Sofia/Documents/GitHub/Final_Project_Airbnb/results/rf_vip')
write_rds(rf_vip, file = '/Users/Sofia/Documents/GitHub/Final_Project_Airbnb/results/rf_vip')
```

